---
Organizations:
    - &OrdererOrg
        Name: ElectionCommissionMSP
        ID: ElectionCommissionMSP
        MSPDir: ../organizations/ordererOrganizations/election-commission.gov.in/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('ElectionCommissionMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('ElectionCommissionMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('ElectionCommissionMSP.admin')"

    - &StateElectionOffice
        Name: StateElectionOfficeMSP
        ID: StateElectionOfficeMSP
        MSPDir: ../organizations/peerOrganizations/state.gov.in/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('StateElectionOfficeMSP.admin', 'StateElectionOfficeMSP.peer', 'StateElectionOfficeMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('StateElectionOfficeMSP.admin', 'StateElectionOfficeMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('StateElectionOfficeMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('StateElectionOfficeMSP.peer')"

    - &DistrictElectionOffice
        Name: DistrictElectionOfficeMSP
        ID: DistrictElectionOfficeMSP
        MSPDir: ../organizations/peerOrganizations/district.gov.in/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('DistrictElectionOfficeMSP.admin', 'DistrictElectionOfficeMSP.peer', 'DistrictElectionOfficeMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('DistrictElectionOfficeMSP.admin', 'DistrictElectionOfficeMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('DistrictElectionOfficeMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('DistrictElectionOfficeMSP.peer')"

Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_0: true

Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: solo
    Addresses:
        - orderer.election-commission.gov.in:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

Profiles:
    VotingOrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            VotingConsortium:
                Organizations:
                    - *StateElectionOffice
                    - *DistrictElectionOffice

    VotingChannel:
        Consortium: VotingConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *StateElectionOffice
                - *DistrictElectionOffice
            Capabilities:
                <<: *ApplicationCapabilities
